config/routes.rb
Techmeet::Application.routes.draw do
  devise_for :users

  resources :users

  root :to => "pages#signin"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :name, :email
  validates :name, :presence => true
  validates :email, :presence => true
end
# == Schema Information
#
# Table name: users
#
#  id                     :integer(4)      not null, primary key
#  name                   :string(255)
#  created_at             :datetime        not null
#  updated_at             :datetime        not null
#  email                  :string(255)     default(""), not null
#  encrypted_password     :string(255)     default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer(4)      default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def signin
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @title = "Member list"
    @users = User.all
  end
  def new
    @title = "New Member"
    @user = User.new
  end
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Welcome to Techmeet"
      redirect_to @user
    else
      flash[:alert] = "User account has not been created."
      render :action => "new"
    end
  end
  def show
    @user = User.find(params[:id])
    @title = @user.name
  end
  def edit
    @user = User.find(params[:id])
    @title = "Edit account"
  end
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:notice]="Account has been updated"
      redirect_to @account
    else
      flash[:alert]="Account has not been updated"
      render 'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
     @base_title = "Techmeet"
     if @title.nil?
       @base_title
     else
       "#{@base_title} | #{@title}"
     end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
</footer>

app/views/layouts/_header.html.erb
<header>
	<nav>
		<% if @user.nil? %> 
		<%= link_to "Sign Up", new_user_path %>
		<% else %>
		<%= link_to "Sign out", '#' %>
		<% end %>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/signin.html.erb
<h1>Pages#signin</h1>
<p>Find me in app/views/pages/signin.html.erb</p>

app/views/pages/signup.html.erb
<h1>Pages#signup</h1>
<p>Find me in app/views/pages/signup.html.erb</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<%= f.error_messages %>
<p>
<%= f.label :name %><br />
<%= f.text_field :name %>
</p>
<p>
<%= f.label :email %><br />
<%= f.text_field :email%>
</p>
<p>
<%= f.label :password %>
<%= f.password_field :password %>
</p>
<p>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
</p>
<%= f.submit "Join Techmeet"%>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Account</h1>
<%= render "form" %>

app/views/users/index.html.erb
<h1>Members</h1>
<ul>
<%= @users.each do |account| %>
  <li><%= link_to account.name, account %></li>
<% end %>
</ul>

app/views/users/new.html.erb
<h2>New User<h2>
<%= render "form" %>